Update LightGCN
xue-pai/Open-CF-Benchmark pull request #3
Opened 2021-03-12 06:13 UTC by ACnoWA

2021-03-14 12:38 UTC, jimzhu requested changes
1, LightGCN_lib --> LightGCN_TF, 保留folder中的README和LICENCE
2. benchmarks/LightGCN/LightGCN.py 都是原始代码，放在LightGCN_lib原始位置。可将__main__该为函数main()，再新写一个script放在benchmark中进行调用
3. LightGCN.py的开头部分写的是NGCF方法，需要改成LightGCN说明
4. markdown文件中"Environments | Dataset | Code | Results | Logs" 按这个顺序来写，代码部分的说明需要确定到原始代码版本。参考https://github.com/xue-pai/Open-CF-Benchmark/blob/master/benchmarks/SLIM/SLIM_amazonbooks_x0.md  
5. Results中的结果需注明指标@K
6. results.md中link的超链接使用相对引用，如(./LightGCN/xxx.md)

2021-03-21 14:16 UTC, jimzhu reviewed
1. /external/LightGCN_TF/lightgcn_tf.py#L11这里改一下
2. markdown中code部分需要写明复现步骤，如果跑的时候用了C++ evaluator，需要在script那里记录下怎么配置。

2021-03-23 03:24 UTC, xpai commented
https://github.com/ACnoWA/Open-CF-Benchmark/blob/master/benchmarks/LightGCN/LightGCN.py#L9   这行的args.data_path在script里没有传入，会报错吧。你得用这个repo跑一下看能不能正常跑起来。

2021-03-23 03:29 UTC, xpai commented
md里Dataset那补充一下，需要把"train.txt"和"test.txt"放在xxxxx_x0目录。

2021-03-23 03:45 UTC, ACnoWA commented
> https://github.com/ACnoWA/Open-CF-Benchmark/blob/master/benchmarks/LightGCN/LightGCN.py#L9 这行的args.data_path在script里没有传入，会报错吧。你得用这个repo跑一下看能不能正常跑起来。

老师 这个data_path有设定的默认值，是他们的相对路径。在push之前我都有在本地先对三个数据集进行运行测试呢，正常运行了之后才更新的。

2021-03-23 07:09 UTC, merged